// <auto-generated />
using System;
using HabitHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HabitHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HabitHub.Api.Models.Habit", b =>
                {
                    b.Property<Guid>("HabitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HabitState")
                        .HasColumnType("integer");

                    b.Property<Guid>("HabitTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("HabitType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("HabitId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("HabitTeamId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("HabitHub.Api.Models.HabitEntry", b =>
                {
                    b.Property<Guid>("HabitEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<float?>("Value")
                        .HasColumnType("real");

                    b.HasKey("HabitEntryId");

                    b.HasIndex("HabitId");

                    b.HasIndex("MemberId");

                    b.ToTable("HabitEntries");
                });

            modelBuilder.Entity("HabitHub.Api.Models.HabitTeam", b =>
                {
                    b.Property<Guid>("HabitTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HabitTeamId");

                    b.HasIndex("CreatorId");

                    b.ToTable("HabitTeams");
                });

            modelBuilder.Entity("HabitHub.Api.Models.InviteCode", b =>
                {
                    b.Property<Guid>("InviteCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CodeStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HabitTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("InviteCodeId");

                    b.HasIndex("HabitTeamId");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Membership", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HabitTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("MembershipId");

                    b.HasIndex("HabitTeamId");

                    b.HasIndex("MemberId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId");

                    b.HasIndex("MemberId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Reminder", b =>
                {
                    b.Property<Guid>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("ReminderId");

                    b.HasIndex("HabitId");

                    b.HasIndex("MemberId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("SessionId");

                    b.HasIndex("MemberId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("HabitHub.Api.Models.TeamChat", b =>
                {
                    b.Property<Guid>("TeamChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HabitTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamChatId");

                    b.HasIndex("HabitTeamId")
                        .IsUnique();

                    b.ToTable("TeamChats");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Habit", b =>
                {
                    b.HasOne("HabitHub.Api.Models.Member", "Creator")
                        .WithMany("CreatedHabits")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HabitHub.Api.Models.HabitTeam", "Team")
                        .WithMany("Habits")
                        .HasForeignKey("HabitTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HabitHub.Api.Models.HabitEntry", b =>
                {
                    b.HasOne("HabitHub.Api.Models.Habit", "Habit")
                        .WithMany("Entries")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HabitHub.Api.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("HabitHub.Api.Models.HabitTeam", b =>
                {
                    b.HasOne("HabitHub.Api.Models.Member", "Creator")
                        .WithMany("CreatedTeams")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("HabitHub.Api.Models.InviteCode", b =>
                {
                    b.HasOne("HabitHub.Api.Models.HabitTeam", "Team")
                        .WithMany("InviteCodes")
                        .HasForeignKey("HabitTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Membership", b =>
                {
                    b.HasOne("HabitHub.Api.Models.HabitTeam", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("HabitTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HabitHub.Api.Models.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Message", b =>
                {
                    b.HasOne("HabitHub.Api.Models.TeamChat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HabitHub.Api.Models.Member", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Notification", b =>
                {
                    b.HasOne("HabitHub.Api.Models.Member", "Member")
                        .WithMany("Notifications")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Reminder", b =>
                {
                    b.HasOne("HabitHub.Api.Models.Habit", "Habit")
                        .WithMany("Reminders")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HabitHub.Api.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Session", b =>
                {
                    b.HasOne("HabitHub.Api.Models.Member", "Member")
                        .WithMany("Sessions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("HabitHub.Api.Models.TeamChat", b =>
                {
                    b.HasOne("HabitHub.Api.Models.HabitTeam", "Team")
                        .WithOne("Chat")
                        .HasForeignKey("HabitHub.Api.Models.TeamChat", "HabitTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Habit", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("HabitHub.Api.Models.HabitTeam", b =>
                {
                    b.Navigation("Chat")
                        .IsRequired();

                    b.Navigation("Habits");

                    b.Navigation("InviteCodes");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("HabitHub.Api.Models.Member", b =>
                {
                    b.Navigation("CreatedHabits");

                    b.Navigation("CreatedTeams");

                    b.Navigation("Memberships");

                    b.Navigation("Notifications");

                    b.Navigation("SentMessages");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HabitHub.Api.Models.TeamChat", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
